library identifier: "pipeline-library@v1.6",
retriever: modernSCM(
  [
    $class: "GitSCMSource",
    remote: "https://github.com/redhat-cop/pipeline-library.git"
  ]
)

openshift.withCluster() {
  env.NAMESPACE = openshift.project()
  env.POM_FILE = env.BUILD_CONTEXT_DIR ? "${env.BUILD_CONTEXT_DIR}/pom.xml" : "pom.xml"
  echo "Starting Pipeline for ${env.APP_NAME}..."
  env.BUILD = "${env.NAMESPACE_BUILD}"
  env.DEV = "${env.NAMESPACE_DEV}"
  env.STAGE = "${env.NAMESPACE_STAGE}"
  env.PROD = "${env.NAMESPACE_PROD}"
}
appSourceUrl = "https://github.com/crystalanvy/DevOpsRepo.git"
appSourceRef = "main"
appFolder = "app"
appName="hello-java"

pipeline {
  // Use Jenkins Maven slave
  // Jenkins will dynamically provision this as OpenShift Pod
  // All the stages and steps of this Pipeline will be executed on this Pod
  // After Pipeline completes the Pod is killed so every run will have clean
  // workspace
  agent {
    label 'maven'
  }

  // Pipeline Stages start here
  // Requeres at least one stage
  stages {

    // Checkout source code
    // This is required as Pipeline code is originally checkedout to
    // Jenkins Master but this will also pull this same code to this slave
    stage('Git Checkout') {
      steps {        
          git url: "${appSourceUrl}", branch: "${appSourceRef}"
      }
    }
    
    // Build Container Image using the artifacts produced in previous stages
    stage('Build Container Image'){
      steps {
        sh """
          ls target/*
          rm -rf oc-build && mkdir -p oc-build/deployments
          for t in \$(echo "jar;war;ear" | tr ";" "\\n"); do
            cp -rfv ./target/*.\$t oc-build/deployments/ 2> /dev/null || echo "No \$t files"
          done
        """
        binaryBuild(projectName: env.BUILD, buildConfigName: env.APP_NAME, buildFromPath: "oc-build")
      }
    }

    stage('Promote from Build to Dev') {
      steps {
        input message: 'Promote application to Production?'
      }
    }

    stage ('Verify Deployment to Dev') {
      steps {
        input message: 'Promote application to Production?'
      }
    }

    stage('Promote from Dev to Stage') {
      steps {
        input message: 'Promote application to Production?'
      }
    }

    stage ('Verify Deployment to Stage') {
      steps {
        input message: 'Promote application to Production?'
      }
    }

    stage('Promotion gate') {
      steps {
        script {
          input message: 'Promote application to Production?'
        }
      }
    }

    stage('Promote from Stage to Prod') {
      steps {
        input message: 'Promote application to Production?'
      }
    }

    stage ('Verify Deployment to Prod') {
      steps {
        input message: 'Promote application to Production?'
      }
    }
  }
}
